import csv
import random
from pathlib import Path

random.seed(42)

TEMPLATES = {
    "billing": [
        # clear billing
        "I was charged twice this month and need a refund.",
        "My invoice shows an incorrect amount.",
        "I cancelled my subscription but I'm still being billed.",
        "The payment failed but the charge still appeared on my card.",
        "I need a receipt for my last payment.",
        "I was charged for a plan I never upgraded to.",
        "I requested a refund two weeks ago and haven't heard back.",
        "There's an unauthorized charge on my account.",
        "My promo code wasn't applied to my invoice.",
        "I downgraded but was still charged at the higher rate.",
        "I need an invoice with our company's VAT number.",
        "My annual plan renewed without warning and I want a refund.",
        "I'm being billed for a seat I deleted three months ago.",
        "The charge on my bank statement doesn't match my invoice.",
        "I need to dispute a charge from last quarter.",
        # billing + complaint overlap
        "Charged again without authorization and nobody is helping me sort it out.",
        "Been billed incorrectly for two months, support keeps ignoring me.",
        "Wrong invoice amount and I've had zero response from your team.",
        "I keep getting overcharged and no one will fix it.",
        "My refund was promised a week ago and still hasn't appeared — totally unacceptable.",
        # billing + technical overlap
        "Can't access my invoices, the billing page throws an error every time.",
        "Payment page crashes when I try to update my card.",
        "My billing portal won't load so I can't even see what I'm being charged.",
        "Download invoice button does nothing, I can't get my receipt.",
        "The upgrade flow charged me twice because the page errored mid-payment.",
        # short / vague
        "Wrong charge on my account.",
        "Overcharged again.",
        "Need a refund asap.",
        "Double billed this month.",
        "Incorrect invoice.",
        "Charge I didn't authorize.",
        "Still being billed after cancelling.",
        # informal / noisy
        "got charged twice wtf",
        "why am i being billed for this??",
        "charged me for something i didnt buy",
        "pls refund my last payment",
        "invoice is wrong again, 3rd time this quarter",
        "u guys billed me for the wrong plan",
        # ambiguous — billing primary, complaint/other vocabulary bleeds in
        "I've been waiting on a refund for two weeks and I'm really frustrated.",
        "Why was I charged more than expected? Nobody has explained this to me.",
        "I need help understanding this charge — it doesn't match anything on my plan.",
        "I think there's a billing error but I'm not sure, can someone look into it?",
        "My payment didn't go through but I'm not sure if I'm still subscribed.",
        "Can I get a breakdown of what I'm actually paying for each month?",
        "I'm confused about my invoice and could use some help figuring it out.",
        "I've been trying to sort out an incorrect charge but I keep hitting a wall.",
        "The invoice section isn't showing what I expect — could be a bug or a billing issue.",
        "I'm not happy about being charged after cancelling — I need this resolved.",
        "I was charged but I don't see it reflected in my account status.",
        "Refund request still pending, just wanted to check on the status.",
        "Not sure if this is a billing error or a system glitch, but I was double charged.",
        "I got an invoice by email but my account still shows as unpaid.",
        "My card was charged but the subscription didn't activate.",
        "I don't understand the difference between what I'm being charged and my plan price.",
        "Overcharged this month — I'd like a credit or refund applied to my next bill.",
        "I need to update payment info but also want to confirm my current charge is correct.",
        "I should be on the discounted plan but my invoice shows the full rate.",
        "Payment went through twice and I'd like one of them refunded as soon as possible.",
        "My receipts don't show up in the billing portal and I need them for tax purposes.",
        "I think I'm being charged for features I'm not using — how do I check?",
        "Bill came in higher than usual and I want to understand why before disputing it.",
    ],
    "technical_issue": [
        # clear technical
        "I can't log in to my account even with the correct password.",
        "The app crashes immediately when I try to open it.",
        "I'm getting a 500 error every time I load the dashboard.",
        "Data sync stopped working two days ago.",
        "File uploads fail with no error message.",
        "Two-factor auth isn't sending the SMS code.",
        "I keep getting logged out every few minutes.",
        "The mobile app loads infinitely and never shows content.",
        "API calls are timing out from our servers.",
        "I can't reset my password — the email link is broken.",
        "Reports generate with completely wrong date ranges.",
        "Dashboard widgets won't load in any browser.",
        "The browser extension broke after a Chrome update.",
        "Webhook events aren't being delivered to our endpoint.",
        "My account was locked by login attempts I didn't make.",
        # technical + feature_request overlap
        "Export keeps failing — can you fix or completely rebuild it?",
        "The search is so broken it might as well not exist, needs a total overhaul.",
        "Mobile app is basically unusable, it needs serious work.",
        "The import tool fails every time, this feature needs to be rethought.",
        "Notifications are broken and honestly the whole system needs a redesign.",
        # technical + complaint overlap
        "Nothing has worked since the last update, this is a complete disaster.",
        "App has been down all morning and no one has communicated anything.",
        "Sync is broken again, third time this month, totally unreliable.",
        "Login is broken and I've been waiting hours for someone to help.",
        "Site is down and your status page says everything is fine — that's a lie.",
        # short / vague
        "App broken.",
        "Can't log in.",
        "Keeps crashing.",
        "Page won't load.",
        "Getting errors.",
        "Nothing is working.",
        "Something broke after the update.",
        # informal / noisy
        "app keeps crashing lol fix pls",
        "site down again???",
        "login broke again smh",
        "everything is broken since the update",
        "500 error on every page wtf",
        "cant get in to my account at all",
        # ambiguous — technical primary, complaint/feature/other vocabulary bleeds in
        "The app is very slow and I'm not sure if that's a bug or just how it works.",
        "Login stopped working — is there an outage or is this just my account?",
        "Something broke after the last update, not sure what exactly.",
        "The export feature doesn't seem to work properly, or maybe I'm using it wrong.",
        "I can't tell if the integration is broken or just not set up correctly.",
        "The dashboard seems off — some numbers look wrong, is this a known issue?",
        "Not getting any notifications — could be a setting or a technical problem.",
        "The page loads but nothing is clickable, very frustrating.",
        "I followed the setup guide but it still isn't working — not sure where I went wrong.",
        "Reports are taking forever to load — is this a performance issue or expected?",
        "The sync feature seems unreliable — it works sometimes and fails other times.",
        "I'm getting occasional errors but they're not consistent, hard to reproduce.",
        "The mobile and desktop versions behave differently — is that a bug?",
        "Some features seem to be missing from my account — maybe a permissions issue?",
        "I can't upload files larger than a few MB — is there a limit I'm not aware of?",
        "The search results don't seem accurate — are there known issues with search?",
        "Something seems wrong with my data — numbers changed overnight.",
        "The API works inconsistently — sometimes it returns data, sometimes it times out.",
        "I'm not sure if the feature I need exists or if it's just broken on my end.",
        "The app is harder to use after the update — a few things seem to have regressed.",
        "Can't complete the setup — the wizard seems to skip a step or loop.",
        "My team sees different data than I do on the same screen — is that normal?",
        "The tool works but it's very slow, is there a way to speed it up?",
    ],
    "feature_request": [
        # clear feature requests
        "It would be great to have a dark mode option.",
        "Can you add bulk export functionality?",
        "Please add two-factor authentication to the login flow.",
        "Can we get a public API for third-party integrations?",
        "Keyboard shortcuts throughout the app would really help.",
        "Can you add support for importing data from Excel?",
        "I'd like to assign tickets to specific team members.",
        "Scheduled and emailed reports would save us a lot of time.",
        "Can you add Markdown formatting in comments?",
        "A Slack or Teams integration would be very useful.",
        "I'd love a read-only view I can share with clients.",
        "Custom fields on tickets would make this much more useful.",
        "An audit log of account changes would help with compliance.",
        "Can you add native Jira integration?",
        "Sub-tasks within a parent ticket would really help us.",
        # feature_request + complaint overlap
        "Why is there still no dark mode? This is really frustrating.",
        "Really need an undo button — I've lost hours of work because it's missing.",
        "The lack of offline mode is genuinely killing our team's productivity.",
        "No bulk export after all this time? Other tools had this years ago.",
        "Still no API? How are we supposed to integrate this with anything?",
        # feature_request + technical overlap
        "The export feature is too limited and constantly breaks — it needs a proper rebuild.",
        "The mobile app needs offline support and a lot of bug fixes before it's usable.",
        "Search is weak and broken, needs both fixes and new capabilities.",
        "The reporting module is slow and limited — please improve performance and add filters.",
        "Can you add dark mode? The current UI is hard on the eyes and causes eye strain.",
        # short / vague
        "Need better mobile app.",
        "Want API access.",
        "Add dark mode please.",
        "Need bulk export.",
        "Please add Slack integration.",
        "Would love offline mode.",
        "Custom fields would help.",
        # informal / noisy
        "pls add bulk export",
        "dark mode when??",
        "really want a desktop app tbh",
        "can u add undo please",
        "need offline mode badly",
        "why no api yet",
        # ambiguous — feature_request primary, other/complaint/technical vocabulary bleeds in
        "Is there a way to export data in bulk? I couldn't find the option.",
        "Does the platform support dark mode? If not, would love to see it added.",
        "Is it possible to assign tickets to team members, or is that not a feature yet?",
        "Can I schedule reports to be emailed automatically, or is that something you'd consider adding?",
        "Is there an API available, or is that something on the roadmap?",
        "Would it be possible to add more granular permission controls in the future?",
        "I couldn't find a way to merge duplicate tickets — is that something you plan to add?",
        "Is there a native desktop app, or is browser-only the plan going forward?",
        "The current notification options are quite limited — any plans to improve them?",
        "I wish I could filter reports by custom date ranges — is that on the roadmap?",
        "Looking for a way to set task priorities — does this exist or is it planned?",
        "I'd love to see better keyboard navigation — accessibility is important to our team.",
        "Is multi-language support planned? Our team is international.",
        "Would be great to have an undo option for bulk actions — lost some data accidentally.",
        "Is there a way to archive old projects? I don't want to delete them but they clutter the view.",
        "Can I get a CSV export of all my tickets? The current export options are limited.",
        "Is there a way to integrate with our existing tools, or is that a future feature?",
        "Would love a time-tracking option built into tasks — does that exist anywhere?",
        "Is there any way to get read-only client access, or would that be a new feature?",
        "I need conditional logic in forms — is that supported or in development?",
        "Would appreciate an activity log for compliance — is that available?",
        "Is there a recurring task option I'm missing, or is that not yet available?",
        "I'd like to see better mobile support — the current app is functional but limited.",
    ],
    "complaint": [
        # clear complaints
        "Your customer service is absolutely terrible.",
        "I've been waiting three days for a response and no one has helped.",
        "I'm extremely disappointed with the level of service I've received.",
        "Your team keeps closing my ticket without resolving anything.",
        "I've sent four emails and haven't received a single reply.",
        "The support agent I spoke with was rude and dismissive.",
        "I was promised a callback that never came.",
        "I asked to speak with a supervisor and was refused.",
        "I have to re-explain my issue to every new agent — no continuity at all.",
        "The ticket was marked resolved without my confirmation.",
        "Your SLA says 4-hour response — I've been waiting 2 days.",
        "I can't believe how poorly this situation has been handled.",
        "Your platform reliability has been terrible this entire quarter.",
        "I'm actively evaluating competitors because of this experience.",
        "Same problem reported three times with zero progress.",
        # complaint + billing overlap
        "Wrong charges AND terrible support — double failure on your part.",
        "Been overcharged and nobody will fix it, completely unacceptable.",
        "Your billing is wrong and your team doesn't seem to care at all.",
        "Charged incorrectly for two months and support has ghosted me.",
        "You took money from me without authorization and support is ignoring my emails.",
        # complaint + technical overlap
        "Nothing works and your support team doesn't seem to care.",
        "App has been broken for days and I can't get anyone to respond.",
        "Your product is broken and your team is useless — worst combo possible.",
        "Site down, no communication, no ETA — this is embarrassing.",
        "Every feature is broken and support keeps sending useless canned responses.",
        # short / vague
        "This is unacceptable.",
        "Terrible service.",
        "Very disappointed.",
        "Completely let down.",
        "Worst experience ever.",
        "No one is helping me.",
        "Fed up with this company.",
        # informal / noisy
        "worst support ever lol",
        "your team is absolutely hopeless",
        "done with this service honestly",
        "i give up, no one helps me here",
        "this is a joke right??",
        "never felt so ignored by a company",
        # ambiguous — complaint primary, technical/billing/other vocabulary bleeds in
        "Really unhappy with how the product has been performing lately.",
        "Multiple issues have gone unresolved and I'm losing confidence in this platform.",
        "I'm not satisfied with the service — between the bugs and the slow support, it's too much.",
        "This isn't what I was led to believe when I signed up.",
        "I feel like I'm paying for something that doesn't work reliably.",
        "The product quality and the support quality have both declined noticeably.",
        "I've had a bad experience every time I've needed help — technical or otherwise.",
        "It's been a frustrating month — billing issues and technical problems on top of no support.",
        "I just want the product to work as promised — right now it doesn't.",
        "I've given this several chances but the experience keeps disappointing me.",
        "The communication from your team has been really poor throughout this process.",
        "I'm not angry, just genuinely disappointed — I expected more.",
        "Every interaction with support leaves me feeling worse about using this product.",
        "The product keeps breaking and support keeps promising fixes that never come.",
        "I've been a patient customer but my patience has a limit.",
        "Support closed my ticket again without asking if the issue was resolved.",
        "I reported this problem weeks ago and nothing has improved.",
        "Your team promised to escalate this and I've heard nothing since.",
        "I'm not trying to be difficult — I just want a working product and a real response.",
        "I'd consider staying if someone actually took ownership of my issues.",
        "Between the downtime and the silence from support, I'm starting to look at alternatives.",
        "The product is frustrating to use and reaching support makes it worse.",
        "I feel like a low-priority customer and that's not acceptable.",
    ],
    "other": [
        # clear general inquiries
        "How do I change the email address on my account?",
        "What are your support hours?",
        "How do I add additional users to my plan?",
        "Can you explain the difference between your pricing tiers?",
        "Where can I find documentation for your API?",
        "How do I change my account password?",
        "What happens to my data if I cancel?",
        "What payment methods do you accept?",
        "How do I export all my data?",
        "How do I close my account permanently?",
        "Is your platform GDPR compliant?",
        "Do you have a community forum or knowledge base?",
        "What is your uptime SLA?",
        "Do you offer a nonprofit or educational discount?",
        "Can I pause my subscription without cancelling?",
        # other + billing overlap
        "How do I update my payment details? Is there a fee to change plans?",
        "What happens to unused time if I downgrade mid-cycle?",
        "Can you explain what the pro plan includes versus basic?",
        "How do I get a copy of past invoices for my accountant?",
        "How do I set up annual billing and will I get a discount?",
        # other + technical overlap
        "How do I export my data? The button seems greyed out for me.",
        "How do I reset my password? The usual way isn't working.",
        "Can I use the same account on multiple devices? It keeps logging me out.",
        "How do I enable notifications? I followed the guide but nothing changed.",
        "Where is the status page? I can't tell if the site is down or it's just me.",
        # short / vague
        "Need help with my account.",
        "Quick question about my plan.",
        "Just checking something.",
        "General question.",
        "Looking for information.",
        "Need help please.",
        "How does this work?",
        # informal / noisy
        "hey how do i cancel?",
        "quick q about pricing",
        "where do i find my settings",
        "how do i add more users",
        "is there a free trial",
        "whats the difference between plans",
        # ambiguous — other primary, billing/technical/feature vocabulary bleeds in
        "Can you help me understand what my current plan includes?",
        "I'm trying to figure out if upgrading would be worth it for our team.",
        "How do I know if a payment went through successfully?",
        "Where do I go to report a bug or a problem with the app?",
        "I'm not sure how to get started — can someone walk me through the basics?",
        "How do I check if there's a known outage affecting my account?",
        "I'm trying to understand how user roles and permissions work.",
        "Can I get more storage on my current plan, or do I need to upgrade?",
        "How do I connect the platform to external tools like Slack or Jira?",
        "I'm looking for a way to share access with a client without giving full permissions.",
        "How does data backup work — is it automatic or do I need to do it manually?",
        "I want to understand the cancellation process before I make a decision.",
        "Is there a trial period I can use to test premium features before committing?",
        "How do I find out what features are included in my current plan?",
        "I'm new to the platform and not sure where to begin — any guidance?",
        "Can I migrate from another tool, and if so how does that work?",
        "How do I know when my subscription renews and what it will cost?",
        "I'd like to understand what happens to my data if I switch plans.",
        "Where can I find a comparison of the different plan tiers?",
        "I'm curious about the onboarding process — how long does it usually take?",
        "How do I reach a real person if I have an urgent issue?",
        "Is there a way to test the API before committing to a paid plan?",
        "What's the best way to organize a large team in this platform?",
    ],
}

SAMPLES_PER_CLASS = 200
OUTPUT_PATH = Path(__file__).parent / "data.csv"

rows = []
for label, templates in TEMPLATES.items():
    for text in random.choices(templates, k=SAMPLES_PER_CLASS):
        rows.append({"text": text, "label": label})

random.shuffle(rows)

with open(OUTPUT_PATH, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["text", "label"])
    writer.writeheader()
    writer.writerows(rows)

print(f"Saved {len(rows)} examples → {OUTPUT_PATH}")
